//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalC.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class dinner
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int food_id { get; set; }
        public string serving { get; set; }
        public string date { get; set; }
    
        public virtual foods foods { get; set; }
        public virtual user user { get; set; }
    }
}
